name: .NET

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:

  build: 
    runs-on: windows-latest


    steps:

    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        packageType: 'sdk'
        version: '6.0.x'
        includePreviewVersions: true 
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: warrenbuckley/Setup-MSBuild msbuild ApplicationFormationAspNetRazoe.sln /p:DeployOnBuild=true /p:PublishProfile=IISProfile.pubxml
