name: .NET

on:
  push:
    branches: [ "develop" ] 
  pull_request:
    branches: [ "develop" ]

jobs:

  build: 
    runs-on: ubuntu-latest
 
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '2.2.106'
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.100-preview.4.21255.9'
        include-prerelease: true
    - name: Restore dependencies
      run: dotnet restore     
    - name: Test
      run: dotnet test --no-build --verbosity normal
    - name: Publish
      run: msbuild ApplicationFormationAspNetRazoe.sln /p:DeployOnBuild=true /p:PublishProfile=IISProfile.pubxml
